chore: Remove Media V1
twilio/twilio-node pull request #1001
Opened 2024-01-29 23:29 UTC by califlower

<!--
We appreciate the effort for this pull request but before that please make sure you read the contribution guidelines, then fill out the blanks below.

**All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.**

Fixes https://twilio-productivity.atlassian.net/jira/servicedesk/projects/EDGSUP/queues/custom/28/EDGSUP-194

# Fixes #

Removes twilio lives service (used during a 1 time event) from the helper library so we can deprecate this in api defintions

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-node/blob/main/CONTRIBUTING.md) and my PR follows them
- [x ] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

2024-01-30 09:22 UTC, tiwarishubham635 requested changes
A few references of media are still present in Twilio.ts file like https://github.com/twilio/twilio-node/blob/a27fd8732b80b258304f1f6c9ba025fbf7922a6d/src/rest/Twilio.ts#L105 and https://github.com/twilio/twilio-node/blob/a27fd8732b80b258304f1f6c9ba025fbf7922a6d/src/rest/Twilio.ts#L177
Removing these should pass the tests

2024-01-30 14:39 UTC, califlower commented
sorry I'm removing more files

2024-01-30 16:15 UTC, tiwarishubham635 approved these changes
LGTM!

2024-01-30 17:34 UTC, javierlopezfernandez approved these changes

2024-02-01 17:17 UTC, bnb approved these changes

2024-02-03 02:29 UTC, merged