feat: Regional twr header in the access token
twilio/twilio-node pull request #623
Opened 2020-10-23 21:19 UTC by charliesantos

# Feature #

This PR adds `AccessTokenOptions.region` parameter to support regional authentication. This value will be encoded in the `twr` header of the JWT. If the parameter is not specified or invalid, no `twr` value is added. See this [document](https://docs.google.com/document/d/17HVcWbfysfhrNNEfewO_bnQaDzVTiOw7Mjeg5ITTLCY/edit#heading=h.ykvt29hsgqdp) for more details.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar) [N/A]
- [ ] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-node/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [ ] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file [N/A]
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

2020-10-23 21:30 UTC, eshanholtz commented on spec/unit/jwt/AccessToken.spec.js
> +        it('should not twr header if region is ' + value, function() {
nit: "should not *add* twr..."

2020-10-23 21:41 UTC, eshanholtz commented on spec/unit/jwt/AccessToken.spec.js
> +    it('should accept different algorithm', function() {
nit: algorithm*s*

2020-10-23 21:41 UTC, eshanholtz commented on lib/jwt/AccessToken.js
> +    if (this.region && typeof this.region === 'string') {
While we still have a lodash as a dependency, I'd prefer the second half of this statement be `_.isString(this.region)` for consistency

2020-10-23 23:14 UTC, eshanholtz approved these changes

2020-10-26 04:04 UTC, idelgado requested changes

2020-10-26 04:04 UTC, idelgado commented on lib/jwt/AccessToken.js
> + * @param {string} [options.region] - Home region to use
> The region value associated with this account

2020-10-26 04:04 UTC, idelgado commented on lib/jwt/AccessToken.d.ts
> +     * Home region to use
I think externally we don't use the term `Home`.
> The region value associated with this account

2020-10-26 19:58 UTC, idelgado approved these changes

2020-10-30 16:43 UTC, merged